### ISSUE TITLE
Improve performance via batched-matmul and fused multiplies

### ISSUE THREAD

**Issue by Birch-san** [AminRezaei0x443/memory-efficient-attention#7]
Many thanks for providing this reference implementation.

I tried integrating this into stable-diffusion / diffusers. A fix was required to make it work on Mac (PyTorch MPS backend):  
https://github.com/Birch-san/diffusers/pull/1/commits/04372140a25d7f53549175f1f196599c3e9bf3a5

Knowing that computing attention via `baddbmm()`+`bmm()` can [outperform einsum by 18%](https://github.com/huggingface/diffusers/pull/1203): I tried to rewrite the algorithm to use those.

I compared the speed of my optimized version, against the implementation in this repository.
_this result is for "everything fits in one chunk" perf (i.e. chunk size = max token length). I was unable to compare chunked perf, because although I got chunking working in my version: I wasn't able to get it working in the version in this repository (got some unexpected-shape tensors returned)._

compared to the implementation in this repository:  
my optimized version achieves a **2.78x speedup** in the time it took to generate a 512x512 image with stable-diffusion v2.1-base (i.e. 4096 vision tokens, 5 attention heads, batch size of 2 due to CFG).  

here's my optimized implementation:  
https://github.com/Birch-san/diffusers/pull/1

batched matmuls require a 3D tensor, i.e. `[batch * num_heads, tokens, channels_per_head]`.

code that currently integrates agains this repository's `[batch, q_length, num_heads, qk_depth_per_head]` format can migrate those tensors to the `[batch * num_heads, q_length, channels_per_head]` format favoured by my implementation like so:

```python
query = query.transpose(1,2).flatten(end_dim=1)
key = key.transpose(1,2).flatten(end_dim=1)
value = value.transpose(1,2).flatten(end_dim=1)
```

the result that's returned, remains in `[batch * num_heads, q_length, qk_depth_per_head]` format, and can be restored to `[batch, q_length, num_heads, qk_depth_per_head]` format like so:

```python
result.unflatten(0, (-1, attn.heads)).transpose(1,2)
```

I think a further speedup is possible too: by working out when chunking is **not** needed: we can compute whether unchunked attention would fit into memory, and prefer unchunked attention as a fast-path where possible. this will be useful in a Unet, which runs attention at various resolutions.

**EDIT:**  
I have now added fast-paths for:

- skipping kv-chunking when `kv_chunk_size >= k_tokens`
  - this turns the algorithm into "attention slicing"
- skipping q-chunking when `q_chunk_size >= q_tokens`
- skipping all chunking when the `kv_chunk_size >= k_tokens` and `q_chunk_size >= q_tokens`
- skipping all chunking when the `q@k.T` matmul requires fewer bytes than a user-provided threshold

**Comment by AminRezaei0x443** [comment]
Really nice implementation @Birch-san. Thanks for your detailed description. 

I'd appreciate it if you could make the modifications described above in this repo too and create a PR. Is it possible for you?

**Comment by brkirch** [comment]
I'm looking at getting this implementation added to [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) but neither this package nor Birch-san's modified implementation has a license. Unfortunately if I simply use this package unmodified I won't get these speed optimizations nor Mac support, both of which are needed.

So I'd like to ask both of you:
@Birch-san @AminRezaei0x443 Are okay with [this](https://github.com/brkirch/stable-diffusion-webui/blob/848605fb654a55ee6947335d7df6e13366606fad/modules/sub_quadratic_attention.py) being added to [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)? You would also be credited [on the main project page](https://github.com/brkirch/stable-diffusion-webui/blob/848605fb654a55ee6947335d7df6e13366606fad/README.md) (see the Credits section at the bottom).

**Comment by Birch-san** [comment]
Yup, I'm okay with releasing my contribution under a permissive license. There are some bits of @AminRezaei0x443's code remaining, so good to find out their licensing desires. But I believe my implementation doesn't contain any lines of code from the other contributors to that repository (as I deleted support for masking and callbacks, and the device argument fixes).

**Comment by Birch-san** [comment]
Oh, you might want to read the latest commits I added:  
https://github.com/Birch-san/diffusers/pull/1

I reduced the number of times the key needed to be transposed. This complicates the API slightly. Has a chance of improving performance though.

**Comment by AminRezaei0x443** [comment]
@brkirch Thanks for your interest and I'm glad this library is useful for you. This project is licensed under `MIT`, I updated the repository too.

**Comment by brkirch** [comment]
Thanks! I've [added the license](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/c18add68ef7d2de3617cbbaff864b0c74cfdf6c0/html/licenses.html#L393-L418) to the PR.

@Birch-san I did experiment with https://github.com/Birch-san/diffusers/pull/1/commits/9dc68226a37fcdd0b387a1a20bb69e0d4b0dbb02 but could only get worse performance. I've been using [kulinseth/pytorch](https://github.com/kulinseth/pytorch) instead of PyTorch nightly builds though, as it gets significantly better performance (usually ~25% faster) for MPS than the nightly builds in my testing. Right now most AUTOMATIC1111 users will be on PyTorch 1.12.1 as it is the latest broken for MPS, but due to the significant MPS improvements in PyTorch I'm going to recommend that users consider switching to [kulinseth/pytorch](https://github.com/kulinseth/pytorch) for inference and only use 1.12.1 for training (which unfortunately still doesn't work for MPS in any newer PyTorch).

**Comment by Birch-san** [comment]
> could only get worse performance

okay, that's interesting. I'm skeptical. I measured the impact of pre-transpose on _unchunked_ attention a while back, and it didn't seem to change the perf for better or worse. I haven't measured the difference on _chunked_ attention, but we'd have to agree on chunk sizes to do that.  
benchmarking is pretty hard on MPS because there's no profiler and because GPU temperature seems to influence the results a lot (you may find that the first test has a bit of an edge).

> broken for MPS, […] only use 1.12.1 for training

really? I did some TI training a few weeks ago using commit from Dec 23:  
https://github.com/pytorch/pytorch/commit/789b1437e945336f83c915ab2f2dd283ac472191  
the key thing for training is the `group_norm` fix that landed on Dec 22:  
https://github.com/pytorch/pytorch/commit/fd3a7264ae80332ba5ec8f60446e6d7a2c2276c1
only workaround I needed was running `cumsum` on CPU:  
https://github.com/pytorch/pytorch/issues/89784#issuecomment-1362223626

> [kulinseth/pytorch](https://github.com/kulinseth/pytorch) usually ~25% faster

wow, I wonder which optimization that is. there's a potentially-dramatic optimization that landed in pytorch master yesterday, which probably was available in kulinseth's branch before that:  
https://github.com/pytorch/pytorch/pull/91114

but there could be downsides to early-adoption. there's stuff that may not be ready:  
https://github.com/pytorch/pytorch/issues/90464

**Comment by Birch-san** [comment]
okay yeah, got 12% faster when I updated to latest master. might be that `torch.linear()` optimization.  
https://twitter.com/Birchlabs/status/1611507344302608388

**Comment by brkirch** [comment]
> okay, that's interesting. I'm skeptical. I measured the impact of pre-transpose on _unchunked_ attention a while back, and it didn't seem to change the perf for better or worse. I haven't measured the difference on _chunked_ attention, but we'd have to agree on chunk sizes to do that. benchmarking is pretty hard on MPS because there's no profiler and because GPU temperature seems to influence the results a lot (you may find that the first test has a bit of an edge).

Yeah it is a bit weird. Originally I got significantly worse performance with AttnBlock (several times slower), so as a compromise I tried making the transpose optional (added a `key_needs_transpose` argument for `efficient_dot_product_attention`). Applying the pre-transpose only for cross attention gave ~20% drop in performance for chunked attention, negligable difference for unchunked.

> > broken for MPS, […] only use 1.12.1 for training
> 
> really? I did some TI training a few weeks ago using commit from Dec 23: [pytorch/pytorch@789b143](https://github.com/pytorch/pytorch/commit/789b1437e945336f83c915ab2f2dd283ac472191) the key thing for training is the `group_norm` fix that landed on Dec 22: [pytorch/pytorch@fd3a726](https://github.com/pytorch/pytorch/commit/fd3a7264ae80332ba5ec8f60446e6d7a2c2276c1) only workaround I needed was running `cumsum` on CPU: [pytorch/pytorch#89784 (comment)](https://github.com/pytorch/pytorch/issues/89784#issuecomment-1362223626)

With torch 2.0.0.dev20230106:
```
Traceback (most recent call last):
  File "/Users/brkirch/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 395, in train_embedding
    scaler.scale(loss).backward()
  File "/Users/brkirch/stable-diffusion-webui/venv-torch-2.0-alpha/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/Users/brkirch/stable-diffusion-webui/venv-torch-2.0-alpha/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [MPSFloatType [1, 77, 768]], which is output 0 of MulBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
It could be that I actually need to fix something, but last time I tried changing the in-place operations that did exist it didn't help. Since you have it working I'll do more testing later to see if I can get it fixed.

> > [kulinseth/pytorch](https://github.com/kulinseth/pytorch) usually ~25% faster
> 
> wow, I wonder which optimization that is. there's a potentially-dramatic optimization that landed in pytorch master yesterday, which probably was available in kulinseth's branch before that: [pytorch/pytorch#91114](https://github.com/pytorch/pytorch/pull/91114)

Could be things like [this](https://github.com/kulinseth/pytorch/pull/146), although I see that it [finally has a PR](https://github.com/pytorch/pytorch/pull/91743) for the main branch. Right now even comparing against the latest nightly build I'm still seeing better performance with the other fork.


> but there could be downsides to early-adoption. there's stuff that may not be ready: [pytorch/pytorch#90464](https://github.com/pytorch/pytorch/issues/90464)

Memory usage is a big issue either way. PyTorch 1.12.1 already uses a lot more memory than it should, to the point that nightly builds may be worth using simply for lower memory usage. Unfortunately debugging memory usage seems to be even more difficult than performance.

**Comment by Birch-san** [comment]
okay, you're right: kulinseth's branch is faster than master. I measured it as 10% faster (on float16).  
https://twitter.com/Birchlabs/status/1611525288642613248

also, the [PR](https://github.com/pytorch/pytorch/pull/89436) to which the "memory usage" [issue](https://github.com/pytorch/pytorch/issues/90464) refers… has merged to master anyway lol.

as for reasons why pre-transpose could cause slowdown for chunked attention… hmm maybe avoiding the early transpose sets you up to fail. maybe it forces you to index into lots of locations that are far away from each other, forcing a big read.  
maybe the reason it's neglible for unchunked attention is because you're gonna read the whole thing anyway.  
perhaps adding an early transpose is basically free due to the other reads we're doing in that area around that time.  
perhaps doing lots of late transposes is basically free because it's transposing a small chunk that you're planning to read all of anyway.

**Comment by iamn000b** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
flyinglimao, @emilianobonassi, @big-c-note, @neo1989, @fourseaLee, @a00012025, @MatinJiridity, @berkingurcan, @positonic, @vuvoth, @Phonbopit, @mikedemarais, @dbsc, @jdhyun09, @allemanfredi, @beauwilliams, @alex-alra-arteaga, @0xfuturistic, @shanev, @qf6101, @AbdelStark, @bmiller59, @catsnackattack, @npjd, @pkoscierzynski, @ruyan768, @moskalyk, @sameesiddiqui, @ditorodev, @daryakaviani, @l3lackcurtains, @lonerapier, @han0110, @obatirou, @spartucus, @kvnyu24, @pongib, @Sednaoui, @shakeib98, @Riely007, @0xisk, @ksaitor, @nivida, @jck-blck, @Lee-WonJun, @bingen, @jilgolfo, @alikonuk1, @gaslimitreached, @JesseAbram
